# -*- coding: utf-8 -*-
"""Isi fitur "Panduan Vaksinasi di Indonesia": profil tiap jenis vaksin.

Disusun ulang dengan kalimat sendiri dari Buku Vaksin Indonesia (Nov 2024),
dicocokkan dengan Jadwal Imunisasi Anak IDAI 2024, Jadwal Dewasa PAPDI 2025,
dan rekomendasi POGI 2026 untuk ibu hamil. Dua data produsen di buku sumber
dibetulkan: M-M-R II buatan MSD (bukan Sanofi), Euvax B buatan LG Chem.

Tiap merek punya "foto": nama berkas di app/merek/ (mis. engerix-b.webp).
Berkas yang belum ada diganti ilustrasi vial netral saat aplikasi berjalan.

Bukan pengganti anjuran dokter — disclaimer ini ditampilkan di aplikasi.
"""


def merek(nama, jenis, produsen, foto):
    return {"nama": nama, "jenis": jenis, "produsen": produsen, "foto": foto}


VAKSIN = [
    {
        "id": "hepb", "nama": "Hepatitis B", "mencegah": "Infeksi hati kronis, sirosis & kanker hati",
        "program": True, "untuk": "Anak & dewasa", "kategori": ["Hepatitis B", "DPT / DPT Combo"],
        "fakta": [["Mulai", "Lahir (<24 jam)"], ["Dosis anak", "4–5 dosis"], ["Cara", "Suntik otot"]],
        "merek": [
            merek("Engerix-B", "Hepatitis B, anak & dewasa", "GSK, Inggris", "engerix-b"),
            merek("Vecon", "Hepatitis B, anak & dewasa", "Bio Farma, Indonesia", "vecon"),
            merek("Euvax B", "Hepatitis B, anak & dewasa", "LG Chem, Korea Selatan", "euvax-b"),
            merek("Twinrix", "Kombinasi Hepatitis A + B", "GSK, Inggris", "twinrix"),
        ],
        "beda": ["Engerix-B, Vecon, dan Euvax B sama-sama vaksin Hepatitis B untuk anak dan dewasa; bedanya pada produsen.",
                 "Twinrix sekaligus melindungi dari Hepatitis A dan Hepatitis B."],
        "manfaat": ["Mencegah infeksi virus Hepatitis B yang menular lewat darah, cairan tubuh, hubungan seksual, dan dari ibu ke bayi.",
                    "Infeksi yang menahun dapat merusak hati hingga sirosis dan kanker hati."],
        "jadwal": [
            ["Anak", ["Dosis 0: dalam 24 jam setelah lahir", "Dosis 1–3: usia 2, 3, dan 4 bulan", "Dosis 4 (booster): usia 18 bulan",
                      "Dosis 1–4 umumnya diberikan dalam vaksin kombinasi (Infanrix Hexa, Hexaxim, atau Pentabio)"]],
            ["Dewasa", ["3 dosis: bulan ke-0, 1, dan 6"]],
            ["Twinrix", ["Usia 2–15 tahun: 2 dosis berjarak 6 bulan", "Usia >16 tahun & dewasa: 3 dosis (0–1–6 bulan)"]],
        ],
        "kontra": ["Alergi berat terhadap komponen vaksin", "Pernah alergi berat setelah dosis Hepatitis B sebelumnya",
                   "Sedang demam atau infeksi akut — ditunda dulu"],
        "perhatian": ["Orang dengan sistem imun sangat lemah mungkin perlu dosis tambahan; konsultasikan dengan dokter."],
        "reaksi": ["Demam, sakit kepala, lemas", "Nyeri, bengkak, atau kemerahan di bekas suntikan", "Nafsu makan menurun"],
        "bahaya": ["Tanpa vaksin, tidak ada perlindungan terhadap Hepatitis B yang dapat berkembang menjadi kerusakan hati kronis, sirosis, hingga kanker hati."],
        "faq": [
            ["Perlu cek darah (serologi) sebelum vaksin?", "Tidak wajib. Vaksin tetap boleh diberikan tanpa pemeriksaan serologi."],
            ["Sudah pernah terinfeksi Hepatitis B, perlu vaksin?", "Tidak perlu, karena tubuh sudah membentuk antibodi sendiri."],
            ["Perlu booster setelah 3 dosis lengkap?", "Untuk orang sehat, saat ini belum ada rekomendasi booster."],
            ["Boleh bersamaan dengan vaksin lain?", "Boleh. Suntikkan di lokasi berbeda, atau berjarak sekitar 2,5 cm bila di lokasi yang sama."],
            ["Ibu hamil boleh vaksin Hepatitis B?", "Sebaiknya ditunda. Vaksin yang dianjurkan saat hamil adalah influenza, Tdap, dan RSV."],
        ],
    },
    {
        "id": "polio", "nama": "Polio", "mencegah": "Kelumpuhan permanen akibat virus polio",
        "program": True, "untuk": "Anak & dewasa", "kategori": ["Polio", "DPT / DPT Combo"],
        "fakta": [["Mulai", "Lahir"], ["Bentuk", "Tetes (OPV) & suntik (IPV)"], ["IPV", "Min. 2× sebelum 12 bln"]],
        "merek": [
            merek("bOPV (Polio tetes)", "Polio oral, virus dilemahkan, tipe 1 & 3", "Bio Farma, Indonesia", "bopv"),
            merek("IPV (Polio suntik)", "Polio inaktif, tipe 1, 2 & 3", "Bio Farma, Indonesia", "ipv"),
        ],
        "beda": ["Polio tetes (OPV) berisi virus hidup yang dilemahkan, diteteskan ke mulut.",
                 "Polio suntik (IPV) berisi virus mati, disuntikkan ke otot; juga terkandung dalam vaksin kombinasi DTP (Infanrix Hexa, Hexaxim)."],
        "manfaat": ["Mencegah polio, infeksi saraf yang dapat menyebabkan lumpuh layu permanen, bahkan kematian bila otot pernapasan terkena.",
                    "Polio menular lewat makanan atau minuman yang tercemar; sanitasi buruk memperbesar risikonya."],
        "jadwal": [
            ["Anak (IDAI 2024)", ["Dosis 0: saat lahir – usia 1 bulan", "Dosis 1–3: usia 2, 3, 4 bulan", "Dosis 4 (booster): usia 18 bulan",
                                   "IPV minimal 2 kali sebelum usia 12 bulan (program: usia 4 dan 9 bulan)"]],
            ["Dewasa", ["Bila riwayat polio masa kecil tidak diketahui: IPV 3 dosis (0–1–7 bulan)"]],
        ],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Alergi berat terhadap streptomisin, neomisin, atau polimiksin B",
                   "Sedang infeksi akut", "Sedang memakai obat imunosupresan"],
        "perhatian": ["Anak yang hanya mendapat polio tetes perlu IPV minimal 2 kali (jarak ≥4 minggu) sebelum usia 12 bulan.",
                      "IPV termasuk vaksin wajib di buku kuning (ICV) untuk perjalanan ke negara endemis polio."],
        "reaksi": ["Demam", "Nyeri atau bengkak di bekas suntikan (IPV)", "Nyeri otot"],
        "bahaya": ["Tanpa vaksin, virus polio dapat menyerang saraf pusat dan menyebabkan kelumpuhan hingga kematian."],
        "faq": [
            ["Polio tetes boleh bersamaan dengan PCV dan DTP?", "Boleh, semuanya dapat diberikan dalam satu kunjungan."],
            ["Polio tetes boleh bersamaan dengan rotavirus?", "Boleh di hari yang sama. Bila dipisah, beri jarak minimal 2 minggu."],
            ["Belum dapat IPV sama sekali sebelum usia 12 bulan?", "Tetap bisa dikejar: 2 dosis IPV dengan jarak minimal 4 minggu."],
        ],
    },
    {
        "id": "bcg", "nama": "BCG", "mencegah": "Tuberkulosis (TB/TBC) berat",
        "program": True, "untuk": "Bayi", "kategori": ["BCG (TBC)"],
        "fakta": [["Mulai", "Lahir – <1 bulan"], ["Dosis", "1 kali, 0,05 ml"], ["Lokasi", "Lengan kanan atas"]],
        "merek": [merek("BCG Bio Farma", "Vaksin BCG", "Bio Farma, Indonesia", "bcg-biofarma")],
        "beda": [],
        "manfaat": ["Mencegah tuberkulosis yang disebabkan Mycobacterium tuberculosis, terutama bentuk TB berat pada anak.",
                    "TB menular, merusak paru, dan pada anak sering tampak sebagai berat badan yang sulit naik."],
        "jadwal": [["Bayi", ["Segera setelah lahir atau sebelum usia 1 bulan, satu kali 0,05 ml disuntik di kulit",
                             "Usia lebih dari 3 bulan: lakukan uji tuberkulin dulu; vaksin diberikan bila hasilnya negatif (bila uji tidak tersedia, vaksin tetap boleh diberikan)",
                             "Anak ≥1 tahun & dewasa yang belum pernah BCG: 0,1 ml"]]],
        "kontra": ["Gangguan sistem imun", "Kehamilan", "Uji tuberkulin positif", "Gizi buruk, demam tinggi, atau infeksi kulit luas",
                   "Alergi berat terhadap komponen vaksin", "Pernah terinfeksi TB"],
        "perhatian": ["Bekas suntikan akan memerah lalu membentuk bisul bernanah dalam 2–12 minggu (paling sering 4–6 minggu), kemudian mengering menjadi parut ±2–6 mm. Ini reaksi normal — tidak perlu diobati.",
                      "Bila ibu menderita TB aktif, BCG ditunda sampai bayi dipastikan tidak tertular; bayi mendapat terapi pencegahan TB."],
        "reaksi": ["Bisul bernanah 2–12 minggu setelah vaksin", "Parut kecil 3–5 bulan setelah vaksin"],
        "bahaya": ["Tanpa BCG, anak lebih rentan terkena TB berat yang dapat menyerang paru maupun organ lain dan mengancam nyawa."],
        "faq": [
            ["Bisul BCG keluar nanah, harus bagaimana?", "Jaga kebersihan sekitarnya. Bila perlu kompres dengan NaCl 0,9% atau air matang."],
            ["Kapan perlu ke dokter?", "Bila bengkak hebat, demam tinggi, atau nanah sangat banyak."],
            ["Perlu booster BCG?", "Tidak, saat ini tidak ada rekomendasi booster BCG."],
        ],
    },
    {
        "id": "dtp", "nama": "DTP Combo", "mencegah": "Difteri, tetanus, pertusis, Hib, Hepatitis B, polio",
        "program": True, "untuk": "Anak 6 minggu – 7 tahun", "kategori": ["DPT / DPT Combo"],
        "fakta": [["Mulai", "Usia 6 minggu"], ["Dosis", "5 (dengan booster)"], ["Cara", "Suntik otot"]],
        "merek": [
            merek("Infanrix Hexa", "DTaP-IPV-Hib-Hepatitis B (heksavalen)", "GSK, Inggris", "infanrix-hexa"),
            merek("Hexaxim", "DTaP-IPV-Hib-Hepatitis B (heksavalen)", "Sanofi, Prancis", "hexaxim"),
            merek("Pentabio", "DTwP-Hib-Hepatitis B (pentavalen)", "Bio Farma, Indonesia", "pentabio"),
            merek("Tetraxim", "DTaP-IPV", "Sanofi, Prancis", "tetraxim"),
        ],
        "beda": ["DTaP (acellular, pada vaksin impor) hanya memakai bagian antigen pertusis yang dibutuhkan, sehingga demam lebih jarang.",
                 "DTwP (whole-cell, pada Pentabio) memakai antigen pertusis utuh; reaksi demam, nyeri, dan bengkak lebih sering.",
                 "Heksavalen sudah berisi polio suntik (IPV); pentavalen tidak, sehingga polio diberikan terpisah."],
        "manfaat": ["Difteri membentuk selaput yang menyumbat jalan napas; tetanus menimbulkan kejang dan kekakuan; pertusis menyebabkan batuk rejan berkepanjangan.",
                    "Komponen Hib mencegah radang selaput otak, radang paru, dan infeksi telinga; komponen lain melindungi dari Hepatitis B dan polio."],
        "jadwal": [["Anak", ["Dosis 1–3: usia 2, 3, 4 bulan (atau 2, 4, 6 bulan)", "Dosis 4 (booster): usia 18 bulan",
                             "Dosis 5 (booster): usia 5–7 tahun", "Mulai usia 7 tahun memakai Td/Tdap"]]],
        "kontra": ["Alergi berat terhadap komponen atau dosis DTP sebelumnya", "Ensefalopati dalam 7 hari setelah vaksin sebelumnya",
                   "Sedang sakit berat", "Sedang menjalani terapi imunosupresif"],
        "perhatian": ["Anak dengan kelainan saraf progresif atau kejang yang belum terkontrol sebaiknya menunda vaksin sampai stabil; konsultasikan dengan dokter."],
        "reaksi": ["Demam, rewel", "Nafsu makan menurun", "Diare atau muntah", "Nyeri, bengkak, kemerahan di bekas suntikan",
                   "Benjolan kecil di bekas suntikan yang hilang sendiri dalam beberapa bulan"],
        "bahaya": ["Difteri, tetanus, dan pertusis dapat menyebabkan kerusakan organ, sumbatan napas, dan kematian — difteri menewaskan 2 dari 10 penderita meski sudah diobati.",
                   "Hib dapat merusak otak dan menyebabkan tuli; polio dapat menyebabkan lumpuh permanen."],
        "faq": [
            ["Boleh dengan jadwal 2, 4, 6 bulan?", "Boleh; efektivitas dan keamanannya sama."],
            ["Usia paling awal?", "Usia 6 minggu."],
            ["Terlambat, bisa dikejar?", "Bisa. Di bawah 7 tahun memakai sediaan DTP; di atas 7 tahun memakai Tdap."],
            ["DTaP pasti tanpa reaksi?", "Tidak selalu; reaksinya bergantung respons tubuh tiap anak, meski umumnya lebih ringan."],
        ],
    },
    {
        "id": "td", "nama": "Tdap / Td", "mencegah": "Tetanus, difteri, pertusis (usia 7 tahun ke atas)",
        "program": True, "untuk": "Anak ≥7 tahun & dewasa", "kategori": ["Tetanus"],
        "fakta": [["Mulai", "7 tahun"], ["Ulangan", "Tiap 10 tahun"], ["Ibu hamil", "27–36 minggu"]],
        "merek": [
            merek("Boostrix", "Tdap", "GSK, Inggris", "boostrix"),
            merek("Adacel", "Tdap", "Sanofi, Prancis", "adacel"),
            merek("Bio Td", "Td (tetanus-difteri)", "Bio Farma, Indonesia", "bio-td"),
        ],
        "beda": ["Tdap berisi antigen tetanus, difteri, dan pertusis dengan porsi tetanus lebih dominan.",
                 "Td hanya berisi tetanus dan difteri."],
        "manfaat": ["Mencegah tetanus, difteri, dan pertusis pada anak besar dan dewasa.",
                    "Sebelum menikah dan saat hamil, Tdap/Td melindungi ibu dan bayi dari tetanus neonatorum akibat pemotongan tali pusat yang tidak steril."],
        "jadwal": [["Anak", ["Usia 7 tahun ke atas; booster usia 10–18 tahun", "Program BIAS: Td di kelas 2 dan kelas 5 SD"]],
                   ["Dewasa", ["1 dosis, diulang setiap 10 tahun"]],
                   ["Ibu hamil (POGI)", ["1 dosis Tdap setiap kehamilan, usia kandungan 27–36 minggu"]]],
        "kontra": ["Alergi berat terhadap komponen atau dosis sebelumnya", "Koma atau penurunan kesadaran dalam 7 hari setelah dosis sebelumnya",
                   "Trombositopenia atau kelainan saraf setelah dosis sebelumnya", "Sedang infeksi akut"],
        "perhatian": ["Tunda pada kelainan saraf (kejang, epilepsi) yang belum stabil; konsultasikan dengan dokter."],
        "reaksi": ["Demam, rewel, sakit kepala", "Nyeri atau bengkak di bekas suntikan", "Nyeri otot"],
        "bahaya": ["Tanpa perlindungan, tetanus menimbulkan kekakuan otot yang sangat nyeri dan dapat mematikan; bayi berisiko tetanus neonatorum."],
        "faq": [
            ["Boleh bersamaan dengan vaksin lain?", "Boleh, dalam satu kunjungan."],
            ["Terlambat, bisa dikejar?", "Bisa: 1 dosis untuk usia 7 tahun ke atas, lalu ulangi setiap 10 tahun."],
            ["Kenapa termasuk vaksin pranikah?", "Agar saat hamil ibu sudah terlindungi dari tetanus yang berbahaya bagi ibu dan bayi."],
        ],
    },
    {
        "id": "pcv", "nama": "Pneumonia (PCV)", "mencegah": "Radang paru, radang selaput otak & infeksi telinga",
        "program": True, "untuk": "Bayi hingga lansia", "kategori": ["Pneumococcus"],
        "fakta": [["Mulai", "Usia 2 bulan"], ["Anak", "3 dosis + booster"], ["Dewasa", "1 dosis"]],
        "merek": [
            merek("Prevenar 13", "PCV13, konjugat 13 serotipe", "Pfizer, AS", "prevenar-13"),
            merek("Prevenar 20", "PCV20, konjugat 20 serotipe", "Pfizer, AS", "prevenar-20"),
            merek("Synflorix", "PCV10, konjugat 10 serotipe", "GSK, Inggris", "synflorix"),
            merek("Pneumovax 23", "PPSV23, polisakarida 23 serotipe", "MSD, AS", "pneumovax-23"),
        ],
        "beda": ["Vaksin konjugat (Prevenar, Synflorix) membentuk kekebalan lebih baik daripada polisakarida (Pneumovax 23).",
                 "Prevenar untuk usia 2 bulan hingga dewasa; Synflorix usia 2 bulan – 5 tahun; Pneumovax 23 untuk dewasa ≥19 tahun.",
                 "Prevenar 20 melindungi dari serotipe terbanyak di antara vaksin konjugat saat ini."],
        "manfaat": ["Mencegah penyakit akibat Streptococcus pneumoniae: radang paru, radang selaput otak, dan infeksi telinga tengah pada semua usia.",
                    "Pneumonia adalah penyebab kematian tertinggi pada balita di Indonesia."],
        "jadwal": [["Anak (IDAI 2024)", ["Usia 2, 4, dan 6 bulan", "Booster usia 12–15 bulan", "Program pemerintah: usia 2, 3, dan 12 bulan (PCV13)"]],
                   ["Dewasa & lansia", ["1 dosis untuk perlindungan seumur hidup",
                                        "Sudah PCV13: PPSV23 boleh 8 minggu kemudian; sudah PPSV23: PCV13 setelah 1 tahun"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Sedang sakit berat"],
        "perhatian": ["Bengkak, kemerahan, atau nyeri di bekas suntikan dapat dikompres dingin 10–15 menit, 3–4 kali sehari."],
        "reaksi": ["Demam, rewel", "Nyeri atau bengkak di bekas suntikan", "Nyeri otot"],
        "bahaya": ["Pneumonia dapat berakibat fatal; 25–35% kasusnya terjadi pada anak di bawah 2 tahun."],
        "faq": [
            ["Terlewat pada anak?", "Bisa dikejar; jumlah dosis bergantung usia saat mulai (7–12 bulan, 1–2 tahun, 2–5 tahun) — dokter akan menentukan."],
            ["Dewasa perlu booster?", "Umumnya tidak; booster hanya atas pertimbangan dokter untuk kondisi tertentu."],
            ["Sudah pernah pneumonia, tetap perlu vaksin?", "Ya. Ada lebih dari 100 serotipe; vaksin mencegah serotipe yang belum pernah menginfeksi."],
        ],
    },
    {
        "id": "rv", "nama": "Rotavirus", "mencegah": "Diare berat & dehidrasi pada bayi",
        "program": True, "untuk": "Bayi 6 minggu – 8 bulan", "kategori": ["Rotavirus (diare)"],
        "fakta": [["Mulai", "6–12 minggu"], ["Cara", "Tetes mulut"], ["Batas", "24–32 minggu"]],
        "merek": [
            merek("Rotateq", "Pentavalen (RV5), 5 strain", "MSD, AS", "rotateq"),
            merek("Rotarix", "Monovalen (RV1), 1 strain", "GSK, Inggris", "rotarix"),
        ],
        "beda": ["Rotateq melindungi dari 5 strain dan diberikan 3 dosis; Rotarix 1 strain dan cukup 2 dosis."],
        "manfaat": ["Mencegah infeksi rotavirus penyebab diare berat dan dehidrasi — penyebab kematian kedua tertinggi pada anak di Indonesia setelah pneumonia.",
                    "Rotavirus sangat menular dan dapat bertahan berminggu-minggu di lingkungan tanpa disinfeksi."],
        "jadwal": [["Rotateq (3 dosis)", ["Dosis 1: usia 6–12 minggu", "Dosis 2: 4–10 minggu setelah dosis 1", "Dosis 3: paling lambat usia 32 minggu"]],
                   ["Rotarix (2 dosis)", ["Dosis 1: usia 6–12 minggu", "Dosis 2: jarak minimal 4 minggu, paling lambat usia 24 minggu"]],
                   ["Program pemerintah", ["Usia 2, 3, 4 bulan; dosis ketiga paling lambat usia 6 bulan 29 hari"]]],
        "kontra": ["Alergi berat terhadap komponen atau dosis sebelumnya", "Kelainan sistem imun", "Kelainan saluran cerna",
                   "Sedang sakit sedang–berat, terutama diare atau muntah"],
        "perhatian": ["Vaksin ini tidak melindungi dari diare karena penyebab lain.",
                      "Setelah vaksin, orang tua perlu mewaspadai tanda intususepsi (usus terlipat): rewel hebat, muntah, BAB berdarah."],
        "reaksi": ["Diare atau muntah ringan", "Rewel", "Biasanya hilang sendiri dalam 1–2 hari"],
        "bahaya": ["Tanpa vaksin, bayi rentan diare berat dan dehidrasi yang dapat mengancam nyawa."],
        "faq": [
            ["Sudah pernah kena rotavirus, tetap perlu vaksin?", "Perlu, karena satu kali infeksi belum melindungi dari semua strain."],
            ["Bayi gumoh setelah ditetes, perlu diulang?", "Tidak perlu; lanjutkan dosis berikutnya sesuai jadwal."],
            ["Boleh menyusu sebelum/sesudah vaksin?", "Boleh. Agar tidak gumoh, sebaiknya jeda sekitar 30 menit."],
        ],
    },
    {
        "id": "flu", "nama": "Influenza", "mencegah": "Flu musiman & komplikasinya",
        "program": False, "untuk": "Usia 6 bulan ke atas", "kategori": ["Influenza"],
        "fakta": [["Mulai", "Usia 6 bulan"], ["Ulangan", "Setiap tahun"], ["Ibu hamil", "Trimester mana pun"]],
        "merek": [
            merek("Vaxigrip Tetra", "Kuadrivalen (2 tipe A + 2 tipe B)", "Sanofi, Prancis", "vaxigrip-tetra"),
            merek("Fluarix Tetra", "Kuadrivalen", "GSK, Inggris", "fluarix-tetra"),
            merek("Influvac Tetra", "Kuadrivalen", "Abbott, AS", "influvac-tetra"),
            merek("Flubio", "Trivalen (2 tipe A + 1 tipe B)", "Bio Farma, Indonesia", "flubio"),
        ],
        "beda": ["Vaksin kuadrivalen melindungi dari 4 tipe virus influenza; trivalen dari 3 tipe."],
        "manfaat": ["Mencegah influenza dan komplikasinya — radang paru, sinusitis, infeksi telinga — terutama pada anak, ibu hamil, dan lansia.",
                    "Influenza berbeda dari pilek biasa: demam tinggi, nyeri otot, lemas; pada penderita penyakit kronis dapat memicu kekambuhan berat."],
        "jadwal": [["Anak", ["Di bawah 9 tahun: 2 dosis berjarak 1 bulan pada tahun pertama, lalu 1 dosis setiap tahun", "9 tahun ke atas: 1 dosis setiap tahun"]],
                   ["Dewasa & lansia", ["1 dosis setiap tahun"]],
                   ["Ibu hamil (POGI)", ["1 dosis setiap kehamilan, trimester mana pun; bila terlewat, boleh setelah melahirkan hingga 6 bulan"]]],
        "kontra": ["Alergi berat setelah vaksin influenza sebelumnya", "Riwayat sindrom Guillain-Barré (GBS)", "Sedang sakit berat"],
        "perhatian": ["Alergi berat terhadap telur: tidak diberikan. Alergi telur ringan masih boleh."],
        "reaksi": ["Nyeri, bengkak, atau pegal di bekas suntikan", "Kadang demam, mual, sakit kepala", "Reaksi alergi berat sangat jarang"],
        "bahaya": ["Pada kelompok rentan — bayi, anak, lansia, ibu hamil, tenaga kesehatan, penderita diabetes atau penyakit jantung, paru, dan ginjal — flu dapat berkomplikasi pneumonia, radang otot jantung, hingga kematian."],
        "faq": [
            ["Trivalen atau kuadrivalen, mana lebih baik?", "Pilih yang tersedia dengan perlindungan paling lengkap."],
            ["Dosis kedua anak <9 tahun terlambat, ulang dari awal?", "Tidak perlu; dosis kedua tetap efektif walau terlambat."],
            ["Sudah vaksin tapi masih flu?", "Bisa karena virus lain yang gejalanya mirip, sudah tertular sebelum antibodi terbentuk, atau reaksi ringan pasca vaksin yang hilang dalam 1–2 hari."],
        ],
    },
    {
        "id": "mr", "nama": "MR (Campak-Rubella)", "mencegah": "Campak & campak Jerman (rubella)",
        "program": True, "untuk": "Usia 9 bulan – 16 tahun", "kategori": ["Campak + Rubella"],
        "fakta": [["Mulai", "Usia 9 bulan"], ["Dosis", "3 (9 bln, 18 bln, 5 thn)"], ["Cara", "Suntik bawah kulit"]],
        "merek": [merek("MR Bio Farma", "Vaksin campak-rubella", "Bio Farma, Indonesia", "mr-biofarma")],
        "beda": [],
        "manfaat": ["Mencegah campak, yang menimbulkan ruam, demam, mata berair, batuk, dan dapat berkomplikasi radang paru.",
                    "Mencegah rubella yang pada ibu hamil dapat menyebabkan cacat bawaan atau kematian janin."],
        "jadwal": [["Anak", ["Dosis 1: usia 9 bulan", "Dosis 2: usia 18 bulan (boleh MMR)", "Dosis 3: usia 5 tahun / BIAS kelas 1 (boleh MMR)"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis MR/MMR sebelumnya", "Alergi berat terhadap neomisin atau susu sapi",
                   "Gangguan sistem imun", "Demam atau infeksi akut", "Kehamilan"],
        "perhatian": ["Dapat memengaruhi hasil uji tuberkulin; beri jarak 1 bulan setelah uji tuberkulin.",
                      "Setelah transfusi darah, beri jarak 3 bulan sebelum vaksin MR."],
        "reaksi": ["Nyeri atau bengkak di bekas suntikan", "Demam, rewel", "Ruam tidak menular 7–10 hari setelah vaksin, selama ±2 hari", "Nyeri otot atau sendi"],
        "bahaya": ["Campak dapat menyebabkan infeksi telinga, kejang, kerusakan otak, hingga kematian; rubella saat hamil dapat menyebabkan sindrom rubella kongenital pada bayi."],
        "faq": [
            ["Boleh bersamaan dengan vaksin lain?", "Boleh, di hari yang sama pada lokasi suntik berbeda."],
            ["Terlambat?", "Bila sampai usia 12 bulan belum MR, dapat diberikan MMR."],
            ["Beda MR dan MMR?", "MMR menambah perlindungan terhadap gondongan (mumps)."],
            ["Sudah MR, lanjut MMR?", "Boleh. Usia 18 bulan dan 5 tahun dapat diberi MR atau MMR."],
        ],
    },
    {
        "id": "mmr", "nama": "MMR", "mencegah": "Campak, gondongan & rubella",
        "program": False, "untuk": "Anak & dewasa", "kategori": ["Campak + Rubella"],
        "fakta": [["Anak", "15–18 bln & 5–7 thn"], ["Dewasa", "2 dosis"], ["Hamil", "Tunda 1 bln setelahnya"]],
        "merek": [merek("M-M-R II", "Vaksin campak-gondongan-rubella", "MSD, AS", "mmr-ii")],
        "beda": [],
        "manfaat": ["Mencegah campak, gondongan (radang kelenjar liur yang dapat berkomplikasi radang testis, ovarium, pankreas, atau selaput otak), dan rubella."],
        "jadwal": [["Anak", ["Dosis 1: usia 15–18 bulan", "Dosis 2: usia 5–7 tahun"]],
                   ["Dewasa", ["2 dosis berjarak minimal 28 hari; rencanakan kehamilan minimal 1 bulan setelah dosis kedua"]]],
        "kontra": ["Kehamilan", "Alergi terhadap komponen vaksin", "Gangguan sistem imun", "Mendapat vaksin hidup lain kurang dari 4 minggu sebelumnya"],
        "perhatian": ["Uji tuberkulin sebaiknya dilakukan sebelum atau bersamaan dengan MMR, karena MMR dapat memengaruhi hasilnya."],
        "reaksi": ["Nyeri di bekas suntikan", "Demam atau ruam hari ke-5 sampai ke-12", "Nyeri sendi"],
        "bahaya": ["Tanpa vaksin, rentan terhadap campak, gondongan, dan rubella beserta komplikasinya: radang paru, radang otak, ketulian, hingga cacat janin bila rubella menyerang ibu hamil."],
        "faq": [
            ["Kenapa perlu dosis kedua?", "Sekitar 7% orang belum membentuk kekebalan setelah dosis pertama."],
            ["Sudah 2 dosis saat kecil, perlu booster dewasa?", "Tidak perlu; dua dosis memberi perlindungan seumur hidup."],
            ["Perlu cek lab sebelum/sesudah?", "Tidak perlu."],
        ],
    },
    {
        "id": "je", "nama": "Japanese Encephalitis (JE)", "mencegah": "Radang otak akibat gigitan nyamuk Culex",
        "program": True, "untuk": "Usia 9 bulan ke atas", "kategori": ["Japanese Encephalitis"],
        "fakta": [["Mulai", "Usia 9 bulan"], ["Anak", "2 dosis"], ["Dewasa", "1 dosis"]],
        "merek": [merek("Imojev", "Vaksin Japanese encephalitis", "Sanofi, Prancis", "imojev")],
        "beda": [],
        "manfaat": ["Mencegah radang otak akibat virus JE yang ditularkan nyamuk Culex.",
                    "Indonesia termasuk wilayah endemis — terutama Bali, Kalimantan Barat, NTT, Sulawesi Utara, Yogyakarta, Jawa Barat, dan Jakarta."],
        "jadwal": [["Anak", ["Mulai usia 9 bulan, 2 dosis berjarak 1–2 tahun", "Program pemerintah: usia 10 bulan di daerah endemis"]],
                   ["Dewasa & lansia", ["1 dosis"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Kelainan imun bawaan atau didapat",
                   "Terapi imunosupresif dosis tinggi dalam 4 minggu terakhir", "Demam atau sakit akut berat", "Hamil atau menyusui"],
        "perhatian": ["IDAI menganjurkan anak yang tinggal di atau akan bepergian ke daerah endemis ≥1 bulan untuk mendapat vaksin ini."],
        "reaksi": ["Nyeri, merah, bengkak di bekas suntikan", "Demam (lebih sering pada anak)", "Nyeri otot dan sakit kepala (lebih sering pada dewasa)"],
        "bahaya": ["JE belum ada obat spesifiknya; kasus berat menimbulkan demam, kaku leher, kejang, hingga koma, dan berbahaya bagi janin bila ibu hamil terinfeksi."],
        "faq": [["Ada obatnya?", "Belum ada pengobatan spesifik untuk JE."],
                ["Perlu sebelum ke Bali?", "Dianjurkan, karena kasus terbanyak ditemukan di Bali."]],
    },
    {
        "id": "var", "nama": "Varisela", "mencegah": "Cacar air",
        "program": False, "untuk": "Usia 12 bulan ke atas", "kategori": ["Varicella"],
        "fakta": [["Mulai", "Usia 12 bulan"], ["Dosis", "2"], ["Cara", "Suntik bawah kulit"]],
        "merek": [
            merek("Varicella Bio Farma", "Vaksin cacar air", "Bio Farma, Indonesia", "varicella-biofarma"),
            merek("Varivax", "Vaksin cacar air", "MSD, AS", "varivax"),
            merek("Varilrix", "Vaksin cacar air", "GSK, Inggris", "varilrix"),
        ],
        "beda": [],
        "manfaat": ["Mencegah cacar air akibat virus varicella-zoster yang menular lewat percikan ludah atau kontak dengan lepuh penderita."],
        "jadwal": [["Anak", ["Dosis 1: usia 12 bulan", "Dosis 2: usia 14 bulan (jarak 6 minggu – 3 bulan)"]],
                   ["Usia ≥13 tahun & dewasa", ["Bila belum pernah: 2 dosis berjarak 4–6 minggu"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin (termasuk gelatin dan neomisin) atau dosis sebelumnya", "Kehamilan",
                   "Gangguan imun, leukemia, HIV bergejala, atau terapi steroid dosis tinggi/imunosupresif"],
        "perhatian": ["Bila sudah pernah terkena cacar air, vaksin ini tidak diperlukan."],
        "reaksi": ["Ruam ringan mirip cacar air", "Demam", "Bengkak kemerahan di bekas suntikan"],
        "bahaya": ["Selain bekas luka di kulit, cacar air dapat berkomplikasi radang paru, radang otak, dan sindrom Reye."],
        "faq": [["Anak baru dapat 1 dosis dari jadwal lama, ulang dari awal?", "Tidak; dosis kedua boleh diberikan kapan saja dengan jarak minimal 4–6 minggu."],
                ["Sudah kontak erat dengan penderita?", "Vaksin tetap dianjurkan bila belum pernah sakit, untuk mencegah atau meringankan penyakit."]],
    },
    {
        "id": "hepa", "nama": "Hepatitis A", "mencegah": "Sakit kuning (radang hati akut)",
        "program": False, "untuk": "Usia 12 bulan ke atas", "kategori": ["Hepatitis A"],
        "fakta": [["Mulai", "Usia 12 bulan"], ["Dosis", "2"], ["Jarak", "6–18 bulan"]],
        "merek": [
            merek("Avaxim", "Hepatitis A (anak 80 U, dewasa 160 U)", "Sanofi, Prancis", "avaxim"),
            merek("Havrix", "Hepatitis A (720 & 1440)", "GSK, Inggris", "havrix"),
            merek("Healive", "Hepatitis A", "Sinovac, Tiongkok", "healive"),
            merek("Twinrix", "Kombinasi Hepatitis A + B", "GSK, Inggris", "twinrix"),
        ],
        "beda": ["Avaxim, Havrix, dan Healive mencegah Hepatitis A; Twinrix sekaligus mencegah Hepatitis A dan B."],
        "manfaat": ["Mencegah infeksi virus Hepatitis A yang menular lewat makanan tidak higienis (fekal-oral).",
                    "Indonesia endemis Hepatitis A; vaksin dianjurkan untuk pelancong dan penjamah makanan."],
        "jadwal": [["Anak", ["Dosis 1: usia 12 bulan", "Dosis 2: usia 18 bulan (6–12 bulan kemudian)"]],
                   ["Dewasa", ["2 dosis berjarak 6–12 bulan"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Alergi berat terhadap neomisin", "Kehamilan"],
        "perhatian": [],
        "reaksi": ["Sakit kepala", "Nafsu makan menurun", "Bengkak kemerahan di bekas suntikan"],
        "bahaya": ["Hepatitis A sangat menular dan masih banyak ditemukan di Indonesia."],
        "faq": [["Sudah pernah Hepatitis A?", "Bila terbukti lewat pemeriksaan laboratorium, vaksin tidak perlu."],
                ["Lewat dari jarak antardosis?", "Tidak perlu diulang; lanjutkan saja dosis berikutnya."]],
    },
    {
        "id": "tif", "nama": "Tifoid", "mencegah": "Demam tifoid (tipes)",
        "program": False, "untuk": "Usia 2 tahun ke atas", "kategori": ["Typhoid (Tipes)"],
        "fakta": [["Mulai", "Usia 2 tahun"], ["Ulangan", "Tiap 3 tahun"], ["Cara", "Suntik otot 0,5 ml"]],
        "merek": [merek("Typhim Vi", "Tifoid polisakarida", "Sanofi, Prancis", "typhim-vi")],
        "beda": [],
        "manfaat": ["Mencegah demam tifoid akibat bakteri Salmonella typhi yang menular lewat makanan atau minuman tercemar.",
                    "Indonesia endemis tifoid, dengan rata-rata sekitar 900.000 kasus per tahun."],
        "jadwal": [["Anak & dewasa", ["Mulai usia 2 tahun, 1 dosis, diulang setiap 3 tahun"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Kehamilan", "Usia di bawah 2 tahun"],
        "perhatian": [],
        "reaksi": ["Demam, nyeri otot", "Nyeri dan bengkak di bekas suntikan", "Pingsan, pandangan kabur, atau telinga berdenging sangat jarang"],
        "bahaya": ["Tanpa vaksin, risiko tertular tifoid dan menjadi pembawa kuman tanpa gejala; tanpa pengobatan, sekitar 30% penderita meninggal karena komplikasi."],
        "faq": [["Boleh vaksin setahun sekali?", "Hanya untuk yang sering terinfeksi, atas pemeriksaan dokter spesialis penyakit dalam."],
                ["Pernah tifoid, tetap perlu?", "Sangat dianjurkan agar tidak terinfeksi ulang."],
                ["Siapa yang berisiko?", "Penduduk dan pelancong di daerah endemis, kontak erat pembawa kuman, dan petugas laboratorium."]],
    },
    {
        "id": "hpv", "nama": "HPV", "mencegah": "Kanker serviks & kutil kelamin",
        "program": True, "untuk": "Usia 9 tahun ke atas", "kategori": ["HPV (Kanker Serviks)"],
        "fakta": [["Mulai", "Usia 9 tahun"], ["9–14 thn", "2 dosis"], ["≥15 thn", "3 dosis"]],
        "merek": [
            merek("Gardasil", "Kuadrivalen (4 tipe)", "MSD, AS", "gardasil"),
            merek("Gardasil 9", "Nonavalen (9 tipe)", "MSD, AS", "gardasil-9"),
            merek("Cervarix", "Bivalen (2 tipe)", "GSK, Inggris", "cervarix"),
        ],
        "beda": ["Gardasil melindungi dari 4 tipe dan Gardasil 9 dari 9 tipe HPV penyebab kanker serviks dan kutil kelamin.",
                 "Cervarix melindungi dari 2 tipe HPV penyebab kanker serviks."],
        "manfaat": ["Mencegah infeksi HPV yang menular lewat kontak kulit atau hubungan seksual.",
                    "Kanker serviks adalah satu-satunya kanker yang hampir sepenuhnya dapat dicegah vaksin (>90%) — dan penyebab kematian tertinggi wanita usia produktif di Indonesia."],
        "jadwal": [["Anak (Gardasil, Gardasil 9)", ["Usia 9–14 tahun: 2 dosis (0–6 bulan)", "Usia ≥15 tahun: 3 dosis (0–2–6 bulan)"]],
                   ["Anak (Cervarix)", ["Usia 9–14 tahun: 2 dosis (0–6 bulan)", "Usia ≥15 tahun: 3 dosis (0–1–6 bulan)"]],
                   ["Program BIAS", ["Dosis 1 di kelas 5 dan dosis 2 di kelas 6 SD (siswi)"]],
                   ["Dewasa", ["Gardasil / Gardasil 9: 3 dosis (0–2–6 bulan)", "Cervarix: 3 dosis (0–1–6 bulan)"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Kehamilan"],
        "perhatian": ["Vaksin tidak menggantikan pap smear/IVA; tetap periksa rutin setiap 3 tahun bagi yang sudah aktif secara seksual."],
        "reaksi": ["Demam, sakit kepala", "Nyeri atau bengkak di bekas suntikan", "Nyeri otot"],
        "bahaya": ["HPV tipe 16 dan 18 menyebabkan kanker leher rahim, vagina, vulva, dan penis; tipe 6 dan 11 menyebabkan kutil kelamin."],
        "faq": [
            ["Perlu pap smear sebelum vaksin?", "Tidak; vaksin dapat langsung diberikan apa pun hasil pap smear."],
            ["Pria perlu vaksin HPV?", "Dianjurkan, untuk mencegah kanker penis dan kutil kelamin."],
            ["Hamil sebelum dosis lengkap?", "Lanjutkan sisa dosis setelah melahirkan."],
            ["Lewat dari jarak antardosis?", "Tidak perlu diulang; lanjutkan dosis berikutnya."],
        ],
    },
    {
        "id": "dbd", "nama": "Demam Berdarah (Dengue)", "mencegah": "Demam berdarah dengue",
        "program": False, "untuk": "Usia 6–45 tahun", "kategori": ["Demam Berdarah"],
        "fakta": [["Usia", "6–45 tahun"], ["Dosis", "2, jarak 3 bulan"], ["Skrining", "Tidak perlu"]],
        "merek": [merek("Qdenga", "Dengue tetravalen", "Takeda, Jepang", "qdenga")],
        "beda": [],
        "manfaat": ["Mencegah demam berdarah dengue dari keempat jenis virus dengue yang ditularkan nyamuk.",
                    "Indonesia mencatat lebih dari 100.000 kasus per tahun dengan lebih dari 1.000 kematian."],
        "jadwal": [["Anak & dewasa (IDAI: 6–45 tahun)", ["2 dosis berjarak 3 bulan", "Tidak perlu pemeriksaan serologi sebelum vaksin"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin", "Hamil atau menyusui", "Gangguan imun",
                   "Terapi imunosupresif (kemoterapi, kortikosteroid dosis tinggi ≥14 hari)"],
        "perhatian": [],
        "reaksi": ["Merah, bengkak, atau nyeri di bekas suntikan", "Demam, sakit kepala, nyeri otot, lemas", "Vaksin tidak dapat menyebabkan DBD"],
        "bahaya": ["DBD dapat menimbulkan syok akibat kebocoran cairan pembuluh darah yang berujung kematian."],
        "faq": [["Dosis kedua lebih dari 3 bulan?", "Masih boleh. Bila lewat 12 bulan setelah dosis pertama, dianjurkan mengulang dari dosis pertama."],
                ["Perlu booster?", "Belum ada rekomendasi."],
                ["Sudah pernah DBD, tetap perlu?", "Perlu; satu kali infeksi hanya melindungi dari 1 dari 4 jenis virus."]],
    },
    {
        "id": "men", "nama": "Meningitis", "mencegah": "Infeksi meningokokus (radang selaput otak)",
        "program": False, "untuk": "Usia 9 bulan ke atas · wajib haji & umrah", "kategori": ["Meningitis"],
        "fakta": [["Haji/umrah", "Wajib"], ["Dosis", "1 (dewasa)"], ["ICV", "Berlaku 3–5 thn"]],
        "merek": [
            merek("Menquadfi", "Konjugat, grup A, C, Y, W-135", "Sanofi, Prancis", "menquadfi"),
            merek("Menactra", "Konjugat, grup A, C, Y, W-135", "Sanofi, Prancis", "menactra"),
            merek("Menivax ACYW", "Polisakarida, grup A, C, Y, W-135", "Bio Farma, Indonesia", "menivax"),
        ],
        "beda": ["Menactra dan Menquadfi adalah vaksin konjugat yang disuntik ke otot; Menivax polisakarida disuntik ke bawah kulit.",
                 "Menactra akan digantikan Menquadfi."],
        "manfaat": ["Mencegah infeksi Neisseria meningitidis grup A, C, W, Y yang menyerang selaput otak dan saraf tulang belakang.",
                    "Endemis di Timur Tengah; wajib bagi jemaah haji, umrah, dan pelancong ke negara tertentu."],
        "jadwal": [["Polisakarida (Menivax)", ["1 dosis, mulai usia 2 tahun"]],
                   ["Menactra", ["Usia 9–23 bulan: 2 dosis berjarak 3 bulan", "Usia >24 bulan: 1 dosis"]],
                   ["Menquadfi", ["Usia >12 bulan: 1 dosis"]]],
        "kontra": ["Riwayat sindrom Guillain-Barré", "Demam atau sakit akut", "Alergi berat terhadap komponen vaksin atau dosis sebelumnya",
                   "Epilepsi dan penyakit otak", "Penyakit ginjal, TBC aktif, atau HIV", "Hamil atau berencana hamil dalam 3 bulan setelah vaksin"],
        "perhatian": ["Di buku kuning/ICV, Menivax berlaku 3 tahun; Menactra dan Menquadfi 5 tahun."],
        "reaksi": ["Nyeri otot, sendi, atau kepala", "Nyeri, merah, bengkak di bekas suntikan", "Reaksi berat sangat jarang"],
        "bahaya": ["Meningitis dapat menyebabkan kematian atau kecacatan jangka panjang: tuli, kerusakan otak, gangguan ginjal, dan gangguan saraf."],
        "faq": [],
    },
    {
        "id": "rabies", "nama": "Rabies", "mencegah": "Rabies akibat gigitan/cakaran hewan",
        "program": False, "untuk": "Risiko tinggi & pasca gigitan", "kategori": [],
        "fakta": [["Sebelum gigitan", "3 dosis + booster"], ["Setelah gigitan", "5 dosis"], ["Cara", "Suntik otot 0,5 ml"]],
        "merek": [merek("Verorab", "Rabies inaktif (sel Vero)", "Sanofi, Prancis", "verorab")],
        "beda": [],
        "manfaat": ["Mencegah rabies, infeksi saraf pusat yang menular lewat gigitan atau cakaran hewan terinfeksi — di Indonesia terutama anjing dan kucing.",
                    "Dianjurkan bagi dokter hewan, pekerja kebun binatang, dan setiap orang yang baru digigit hewan berisiko rabies."],
        "jadwal": [["Sebelum tergigit", ["Dosis I: sekarang", "Dosis II: hari ke-7", "Dosis III: hari ke-28", "Booster: 1 tahun dan 5 tahun setelah dosis I"]],
                   ["Setelah tergigit", ["5 dosis: segera, lalu hari ke-3, 7, 14, dan 28 setelah dosis pertama",
                                         "Luka derajat III ditambah imunoglobulin rabies — derajat luka ditentukan dokter"]]],
        "kontra": ["Sebelum tergigit: alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Setelah tergigit: tidak ada kontraindikasi, karena rabies hampir selalu fatal"],
        "perhatian": ["Vaksin harus diberikan tepat sesuai jadwal, tidak boleh kurang atau lebih."],
        "reaksi": ["Nyeri, merah, gatal, bengkak di bekas suntikan", "Demam, menggigil, sakit kepala, mual, nyeri otot, lemas", "Syok anafilaktik sangat jarang"],
        "bahaya": ["Rabies merusak saraf pusat: kelemahan otot, gangguan kesadaran, halusinasi, takut air, hingga kematian."],
        "faq": [["Hewan peliharaan sudah divaksin, pemiliknya perlu?", "Tidak wajib, tetapi tetap dianjurkan bagi pemilik anjing atau kucing."],
                ["Hewan apa saja yang berisiko?", "Selain anjing dan kucing: kelelawar, kuda, kelinci, sapi, musang, tikus, hamster, rakun, dan rubah."]],
    },
    {
        "id": "yf", "nama": "Yellow Fever", "mencegah": "Demam kuning (wajib ke Afrika & Amerika Selatan)",
        "program": False, "untuk": "Usia 9 bulan – 59 tahun", "kategori": [],
        "fakta": [["Dosis", "1 kali"], ["Usia", "9 bln – 59 thn"], ["ICV", "Berlaku 10 tahun"]],
        "merek": [merek("Stamaril", "Yellow fever, virus dilemahkan", "Sanofi, Prancis", "stamaril")],
        "beda": [],
        "manfaat": ["Mencegah yellow fever yang ditularkan nyamuk Aedes aegypti di Afrika dan Amerika Selatan."],
        "jadwal": [["Pelancong", ["1 dosis, usia 9 bulan – 59 tahun, sebelum ke daerah endemis"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin, terutama protein telur", "Alergi berat setelah dosis sebelumnya", "Gangguan imun", "Kehamilan"],
        "perhatian": ["Jangan donor darah sampai 14 hari setelah vaksin.", "Usia 65 tahun ke atas perlu pengawasan karena risiko efek samping serius lebih tinggi."],
        "reaksi": ["Nyeri, merah, gatal, bengkak di bekas suntikan", "Demam, sakit kepala, nyeri otot",
                   "Radang otak, meningitis, atau GBS pernah dilaporkan namun sangat jarang"],
        "bahaya": ["Yellow fever berat menyebabkan perdarahan hebat, gagal jantung, ginjal, dan hati, hingga kematian 7–10 hari setelah gejala."],
        "faq": [["Boleh bersamaan dengan MMR?", "Boleh dalam satu kunjungan; bila dipisah, beri jarak minimal 28 hari."],
                ["Berapa lama perlindungannya?", "Satu dosis memberi perlindungan jangka panjang; di buku kuning berlaku 10 tahun."]],
    },
    {
        "id": "zoster", "nama": "Zoster", "mencegah": "Herpes zoster (cacar api/cacar ular)",
        "program": False, "untuk": "Dewasa ≥50 tahun", "kategori": [],
        "fakta": [["Usia", "≥50 tahun"], ["Dosis", "2, jarak 2–6 bln"], ["Booster", "Tidak perlu"]],
        "merek": [merek("Shingrix", "Herpes zoster rekombinan", "GSK, Inggris", "shingrix")],
        "beda": [],
        "manfaat": ["Satu-satunya perlindungan terhadap herpes zoster, yang timbul ketika virus cacar air yang tertidur di tubuh aktif kembali.",
                    "Pada dewasa sehat ≥50 tahun efektivitasnya >90% dan bertahan setidaknya 7 tahun."],
        "jadwal": [["Dewasa ≥50 tahun", ["2 dosis berjarak 2–6 bulan"]],
                   ["Dewasa ≥19 tahun dengan imun lemah", ["2 dosis berjarak 1–2 bulan"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin", "Sedang terinfeksi herpes zoster", "Kehamilan"],
        "perhatian": ["Setelah sembuh dari herpes zoster, pastikan ruam sudah hilang sebelum vaksin (minimal 2 bulan)."],
        "reaksi": ["Merah dan bengkak di bekas suntikan", "Lelah, nyeri otot, sakit kepala, menggigil, demam, mual — biasanya 2–3 hari"],
        "bahaya": ["Herpes zoster sangat nyeri dan dapat meninggalkan nyeri saraf berkepanjangan (neuralgia pascaherpes), kebutaan, atau gangguan saraf."],
        "faq": [["Sama dengan vaksin varisela?", "Tidak; jenis, dosis, dan cara pemberiannya berbeda, dan Shingrix tidak mencegah cacar air."],
                ["Sudah pernah zoster, boleh vaksin?", "Boleh, minimal 2 bulan setelah sembuh total."],
                ["Perlu booster?", "Belum ada rekomendasi."]],
    },
    {
        "id": "rsv", "nama": "RSV", "mencegah": "Infeksi saluran napas bawah berat (bronkiolitis, pneumonia)",
        "program": False, "untuk": "Ibu hamil 32–36 minggu & lansia", "kategori": [],
        "fakta": [["Ibu hamil", "32–36 minggu"], ["Lansia", "≥60 tahun"], ["Dosis", "1 kali"]],
        "merek": [
            merek("Abrysvo", "RSV tanpa adjuvan", "Pfizer, AS", "abrysvo"),
            merek("Arexvy", "RSV beradjuvan", "GSK, Inggris", "arexvy"),
        ],
        "beda": ["Abrysvo dapat diberikan pada ibu hamil sehingga bayi terlindungi sejak lahir hingga usia 6 bulan, juga untuk dewasa dan lansia.",
                 "Arexvy untuk usia 50–60 tahun yang berisiko dan >60 tahun; tidak untuk ibu hamil dan menyusui."],
        "manfaat": ["RSV menyerang saluran napas bawah dan mudah menular. Bayi baru lahir dan lansia — terutama dengan asma/PPOK, diabetes, penyakit paru atau jantung — paling rentan komplikasi berat."],
        "jadwal": [["Ibu hamil (POGI 2026)", ["1 dosis Abrysvo setiap kehamilan, usia kandungan 32–36 minggu, minimal 14 hari sebelum persalinan"]],
                   ["Dewasa & lansia", ["1 dosis: usia 18–59 tahun berisiko tinggi, dan semua usia >60 tahun"]]],
        "kontra": ["Alergi berat terhadap komponen vaksin atau dosis sebelumnya", "Sedang demam atau sakit akut",
                   "Arexvy: tidak untuk ibu hamil, menyusui, dan usia <50 tahun", "Abrysvo: tidak untuk kehamilan <24 minggu dan anak <18 tahun"],
        "perhatian": ["Abrysvo tidak disarankan diberikan bersamaan dengan vaksin influenza kuadrivalen dan vaksin Tdap."],
        "reaksi": ["Sakit kepala, nyeri sendi, nyeri di bekas suntikan", "Bengkak kemerahan di bekas suntikan"],
        "bahaya": ["Pada lansia RSV dapat berujung perawatan intensif dan pneumonia; pada bayi dapat menyebabkan bronkiolitis dengan gagal napas — paling sering usia 0–3 bulan."],
        "faq": [["Sudah Arexvy, perlu Abrysvo juga?", "Tidak; cukup 1 kali seumur hidup dengan merek apa pun."],
                ["Pernah terinfeksi RSV, boleh vaksin?", "Boleh."], ["Perlu booster?", "Belum ada data."]],
    },
]

# Jadwal imunisasi ibu hamil — Rekomendasi POGI 2026.
JADWAL_HAMIL = [
    ["Influenza", "1 dosis setiap kehamilan, trimester mana pun",
     "Diulang tiap tahun karena perlindungan menurun dan strain virus berubah. Bila tidak divaksin saat hamil, boleh setelah persalinan hingga 6 bulan. (Grade A)"],
    ["Tdap", "1 dosis setiap kehamilan, usia kandungan 27–36 minggu",
     "Bila belum pernah, diberikan setelah melahirkan. Booster saat hamil bila imunisasi terakhir >10 tahun. Keluarga dan pengasuh yang belum divaksin dianjurkan Tdap minimal 2 minggu sebelum kontak dengan bayi. (Bukti 1++, Grade A)"],
    ["RSV", "1 dosis setiap kehamilan, usia kandungan 32–36 minggu",
     "Vaksin RSV bivalen berbasis protein F prefusi (Abrysvo), minimal 14 hari sebelum persalinan agar antibodi sempat berpindah ke janin. (Bukti 1++, Grade A)"],
]

# Ilustrasi kemasan per merek, digambar aplikasi (bukan foto). Bentuk dan warna
# khas kemasan mengacu pada foto di Buku Vaksin Indonesia sebagai referensi;
# tidak ada foto, logo, atau tanda air yang disalin.
#   bentuk: kotak | kotak-spuit (kotak + spuit siap pakai) | vial (deret vial) | tube (tube oral)
#   warna:  [warna utama, warna aksen]
GAYA_MEREK = {
    "engerix-b": ["kotak-spuit", "#2F5DA8", "#E7ECF6"], "vecon": ["kotak", "#3E9B47", "#1F5FA8"],
    "euvax-b": ["kotak", "#2C8FCB", "#E07B2C"], "twinrix": ["kotak-spuit", "#3C6FB6", "#F2D34A"],
    "bopv": ["kotak", "#C8332B", "#1F3F7A"], "ipv": ["vial", "#D7578A", "#F3D9E4"],
    "bcg-biofarma": ["vial", "#2D5FA6", "#DDE6F2"], "infanrix-hexa": ["kotak", "#2A7BC0", "#C8A23C"],
    "hexaxim": ["kotak", "#1E73BE", "#7FB3E0"], "pentabio": ["vial", "#7A4AA0", "#E9E0F2"],
    "tetraxim": ["kotak-spuit", "#2A8FC8", "#C8332B"], "boostrix": ["kotak", "#7B4FA3", "#B9D24A"],
    "adacel": ["kotak", "#5B3E96", "#F2C23A"], "bio-td": ["kotak", "#1F9AAE", "#E04E3A"],
    "prevenar-13": ["kotak", "#7A5BA8", "#C33A6A"], "prevenar-20": ["kotak", "#14707F", "#0F3E5E"],
    "synflorix": ["kotak-spuit", "#3D9A4A", "#E5734A"], "pneumovax-23": ["kotak-spuit", "#1E5FAE", "#7A8AA0"],
    "rotateq": ["tube", "#6B3F9A", "#B79AD6"], "rotarix": ["tube", "#D23B3B", "#F4C6C6"],
    "vaxigrip-tetra": ["kotak-spuit", "#2063B0", "#9BC4EA"], "fluarix-tetra": ["kotak", "#2E8C4A", "#E28A2B"],
    "influvac-tetra": ["kotak", "#E0782C", "#2D5FA6"], "flubio": ["kotak", "#1E9AAE", "#5DBF6A"],
    "mr-biofarma": ["vial", "#7B4AA0", "#C98A3A"], "mmr-ii": ["kotak", "#1E8F9A", "#2D5FA6"],
    "imojev": ["kotak", "#4AA3D8", "#1F5FA8"], "varicella-biofarma": ["kotak", "#8B5AB8", "#3FA7D6"],
    "varivax": ["kotak-spuit", "#1E5FAE", "#46A0C8"], "varilrix": ["kotak-spuit", "#E57AA6", "#2D5FA6"],
    "avaxim": ["kotak-spuit", "#2D5FA6", "#D23B3B"], "havrix": ["kotak-spuit", "#F2C33A", "#2D5FA6"],
    "healive": ["kotak", "#E88AA8", "#8A1F4A"], "typhim-vi": ["kotak-spuit", "#2E9C5A", "#1F5FA8"],
    "gardasil": ["kotak", "#2A6DB5", "#D23B3B"], "gardasil-9": ["kotak", "#1E8FC8", "#D23B3B"],
    "cervarix": ["kotak-spuit", "#E2668E", "#F3A43A"], "qdenga": ["kotak-spuit", "#7A4AA0", "#3A6FB5"],
    "menactra": ["kotak", "#6B4A9E", "#2D5FA6"], "menivax": ["vial", "#3E9B47", "#E8F2DF"],
    "menquadfi": ["kotak", "#2E9C5A", "#2D5FA6"], "verorab": ["kotak", "#C8332B", "#2D5FA6"],
    "stamaril": ["kotak", "#F2C33A", "#C8332B"], "shingrix": ["kotak", "#E8642C", "#C8332B"],
    "arexvy": ["vial", "#F2B33A", "#2D5FA6"], "abrysvo": ["kotak", "#3E4FA0", "#D74A8A"],
}
for _v in VAKSIN:
    for _m in _v["merek"]:
        _m["gaya"] = GAYA_MEREK.get(_m["foto"], ["kotak", "#56C3C7", "#E8488C"])
